version: "3.8"
services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: crud_app
      DB_PORT: 3306
      LOG_DIR: /var/logs/crud
    depends_on:
      - db
    volumes:
      - ./logs:/var/logs/crud

volumes:
  db_data:
